ARG UPSTREAM_REF=rustdesk/rustdesk-server-pro:latest
ARG UPSTREAM_IMAGE=rustdesk/rustdesk-server-pro:latest
ARG UPSTREAM_DIGEST=unknown

FROM ${UPSTREAM_REF}

ARG TARGETARCH
ARG UPSTREAM_IMAGE
ARG UPSTREAM_DIGEST

LABEL upstream.image="${UPSTREAM_IMAGE}"
LABEL upstream.digest="${UPSTREAM_DIGEST}"

COPY dist/ /tmp/license-server-dist/

RUN cp "/tmp/license-server-dist/license-server-${TARGETARCH}" /usr/bin/license-server && \
    chmod +x /usr/bin/license-server && \
    rm -rf /tmp/license-server-dist

RUN mkdir -p /certs && chmod 700 /certs

COPY original_ed25519.pub /certs/original_ed25519.pub

RUN cd /certs && license-server --keygen && \
    HBBS_PATH=/usr/bin/hbbs \
    HBBS_BACKUP_PATH=/usr/bin/hbbs-official \
    ORIGINAL_KEY_PATH=/certs/original_ed25519.pub \
    NEW_KEY_PATH=/certs/id_ed25519.pub \
    license-server --patch

RUN chmod 600 /certs/*

RUN ln -s /certs/ca.crt /usr/local/share/ca-certificates/rustdesk.crt && \
    update-ca-certificates

RUN chmod +x /usr/bin/hbbs

ENV LICENSE_SERVER_CRT=/certs/server.crt

ENV LICENSE_SERVER_PRIV=/certs/server.key

ENV LICENSE_SIGNKEY_PUB=/certs/id_ed25519.pub

ENV LICENSE_SIGNKEY_PRIV=/certs/id_ed25519

ENV LICENSE=UlVTVERFU0tfTElDRU5TRQ==
